# Standards: 0.1
---
- name: Fact docker user
  set_fact:
    docker_user: "{{ docker_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - docker

- become: "{{ (docker_user != ansible_user_id) | bool }}"
  become_user: "{{ docker_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: docker
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - docker

- name: Remove quarantine flag
  register: docker_quarantine
  failed_when: docker_quarantine.rc != 0 and "No such xattr" not in docker_quarantine.stderr
  changed_when: docker_quarantine.rc == 0
  command: xattr -d com.apple.quarantine /Applications/Docker.app
  tags:
    - docker

...
